### ISSUE TITLE
Put a 60 second delay on public only for anyone but yourself.

### ISSUE THREAD

**Issue by fastFox2** [mawburn/portaler-core#86]
A possible way of implementing that could be that the frontend delays the sending to the server. This should get more people to map on the public map.

**Comment by mawburn** [comment]
I'm ok with 90 seconds too. 

I think this would be a good way to encourage more participation in the public map. The frontend could just "hold" it and display it for the user mapping only. Possibly throwing into another local storage variable with a timer in there. 

So it's there if it doesn't send to the server and they refresh the page. 

This also probably means it needs to store the actual UTC time of the expiry instead of the time left. So, it **could** be a bigger lift than I originally thought, but not by much and would probably be worth it.

**Comment by fastFox2** [comment]
If we store the UTC time of expiry we could also add a setting to allow the user to switch frome the time left to the UTC time, and the other way arround. When the way the time left is stored gets stored the time left on royal connections should be cleared up as well. Because at the moment it is always over 1000 hours, I think because of the way it gets set on first time.

**Comment by mawburn** [comment]
Ah yeah good idea, we actually don't have a ticket for that. I think you can make one now. :) @fastFox2 

Tag that under Medium difficulty and new feature. This is a good test to see if you can do that now.

**Comment by fastFox2** [comment]
Closing because the public map got shut down.

**Comment by mawburn** [comment]
Public map is still open. MistWalker map was shut down.
